// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tnpcrxconafliiuhszcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucGNyeGNvbmFmbGlpdWhzemN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5NDMwODcsImV4cCI6MjA5NDUxOTA4N30.JKH9OSsb6Bk62m92E55DMS0WZXrcw6UPzV6RYSvtG4I";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});